{pkgs, ...}: {
  # TPM 2.0 kernel modules required in the initrd for LUKS auto-unlock.
  boot.initrd = {
    availableKernelModules = [
      "tpm"
      "tpm_tis"
      "tpm_crb"
    ];

    # Enable systemd-based initrd — required for systemd-cryptsetup to
    # perform TPM2-based LUKS decryption automatically at boot.
    systemd.enable = true;

    # Explicitly tell systemd-cryptsetup which LUKS device to unlock.
    # "disk-main-luks" is the GPT partition label auto-generated by disko
    # from the `disk.main.luks` attribute path.
  };

  # Keep the TPM2 resource manager available at runtime (useful for
  # userspace tools like systemd-cryptenroll and clevis).
  security.tpm2.enable = true;

  # systemd-cryptenroll is needed to enrol the TPM key into a LUKS slot.
  environment.systemPackages = [pkgs.systemd];
}
