{
  imports = [
    ../common
    ./sops.nix
    ./core-server.nix
    ./security.nix
    ./cloudflared.nix
    ./nvidia.nix
    ./monitoring.nix
    ./monitoring-grafana.nix
    ./storage-layout.nix
    ./container.nix
    ./containers/immich
    ./containers/llama
    ./containers/speaches
    ./containers/open-webui
    ./containers/searxng
    ./containers/hermes
    ./containers/signal-cli
    ./containers/proton-drive
    ./containers/fileflows
    ./containers/blocky
    ./containers/caddy
    ./containers/authelia
    ./containers/zot
    ./containers/bookorbit
    ./containers/home-assistant
    ./containers/paperless
    ./containers/jellyfin
  ];
}
