{
  imports = [
    ./git.nix
    ./firefox.nix
    ./zsh.nix
    ./niri
    ./opencode
    ./catppuccin.nix
    ./quickshell
    ./lazygit.nix
    ./nix-direnv.nix
    ./tidal.nix
    ./yazi.nix
    ./foot.nix
    ./chromium.nix
    ./devtools.nix
    ./heroic.nix
    ./prismlauncher.nix
    ./proton.nix
    ./wifitui.nix
    ./unzip.nix
    ./oculante.nix
    ./codex.nix
    ./obsidian.nix
    ./devenv.nix
    ./vim.nix
  ];
}
